#define CASE_FPMARK_NAN     1
#define CASE_FPMARK_PINF    2
#define CASE_FPMARK_NINF    3
#define CASE_FPMARK_REGULAR 4
const uint8_t FPMARK_NAN     = CASE_FPMARK_NAN;
const uint8_t FPMARK_PINF    = CASE_FPMARK_PINF;
const uint8_t FPMARK_NINF    = CASE_FPMARK_NINF;
const uint8_t FPMARK_REGULAR = CASE_FPMARK_REGULAR;
